Reworked documentation generation and installation. Details: - Remove configure flag used to disable the automatic generation of the   documentation when istalling. - Now 'make html' generates the documentation. - Now 'make install' does not install the documentation, 'make install-html'   does that. The latter two changes follow newer automake conventions. - This also fixes the bug that caused the documentation missing from the   tarball.

diff --git a/doc/Makefile.am b/doc/Makefile.am
--- a/doc/Makefile.am
+++ b/doc/Makefile.am
@@ -1,56 +1,53 @@
-htmldir = $(datadir)/doc/$(PACKAGE)/html
-
 EXTRA_DIST += \
 	doc/Makefile \
-	doc/Doxyfile.in
+	doc/Doxyfile.in \
+	doc/coding_style.dox \
+	doc/dirs.dox \
+	doc/groups.dox \
+	doc/license.dox \
+	doc/mainpage.dox \
+	doc/namespaces.dox \
+	doc/html
 
-doc:
+doc/html:
+	$(MAKE) $(AM_MAKEFLAGS) html
+
+html-local:
 	if test ${doxygen_found} = yes; then \
 	  cd doc; \
 	  doxygen Doxyfile; \
 	  cd ..; \
-	fi
-
-doc-clean:
-	if test ${doxygen_found} = yes; then \
-	  rm -rf doc/html; \
-	  rm -f doc/doxygen.log; \
-	  cd doc; \
-	  doxygen Doxyfile; \
-	  cd ..; \
+	else \
+	  echo; \
+	  echo "Doxygen not found."; \
+	  echo; \
+	  exit 1; \
 	fi
 
 clean-local:
 	-rm -rf doc/html
 	-rm -f doc/doxygen.log
 
-doc/html:
-	$(MAKE) $(AM_MAKEFLAGS) doc-clean
-
 update-external-tags:
 	wget -O doc/libstdc++.tag.tmp http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/libstdc++.tag && \
 	mv doc/libstdc++.tag.tmp doc/libstdc++.tag || \
 	rm doc/libstdc++.tag.tmp
 
-if WANT_DOC
-
-install-data-local: doc/html
+install-html-local: doc/html
 	@$(NORMAL_INSTALL)
-	$(mkinstalldirs) $(DESTDIR)$(htmldir)
-	@dir='doc/html'; shopt -s nullglob; for p in $$dir/*.html $$dir/*.css $$dir/*.png $$dir/*.gif $$dir/*.dot $$dir/*.php $$dir/*.idx $$dir/*.tag ; do \
+	$(mkinstalldirs) $(DESTDIR)$(htmldir)/docs
+	for p in doc/html/*.{html,css,png,map,gif,tag} ; do \
 	  f="`echo $$p | sed -e 's|^.*/||'`"; \
-	  echo " $(INSTALL_DATA) $$p $(DESTDIR)$(htmldir)/$$f"; \
-	  $(INSTALL_DATA) $$p $(DESTDIR)$(htmldir)/$$f; \
+	  echo " $(INSTALL_DATA) $$p $(DESTDIR)$(htmldir)/docs/$$f"; \
+	  $(INSTALL_DATA) $$p $(DESTDIR)$(htmldir)/docs/$$f; \
 	done
 
-uninstall-local: doc/html
+uninstall-local:
 	@$(NORMAL_UNINSTALL)
-	@dir='doc/html'; shopt -s nullglob; for p in $$dir/*.html $$dir/*.css $$dir/*.png $$dir/*.gif $$dir/*.dot $$dir/*.php $$dir/*.idx $$dir/*.tag ; do \
+	for p in doc/html/*.{html,css,png,map,gif,tag} ; do \
 	  f="`echo $$p | sed -e 's|^.*/||'`"; \
-	  echo " rm -f $(DESTDIR)$(htmldir)/$$f"; \
-	  rm -f $(DESTDIR)$(htmldir)/$$f; \
+	  echo " rm -f $(DESTDIR)$(htmldir)/docs/$$f"; \
+	  rm -f $(DESTDIR)$(htmldir)/docs/$$f; \
 	done
 
-endif WANT_DOC
-
-.PHONY: doc doc-clean
+.PHONY: update-external-tags
